apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: cb-kubecd
    provider: github
    repository: go-test-02
  name: cb-kubecd-go-test-02
spec:
  description: Imported application for cb-kubecd/go-test-02
  httpCloneURL: https://github.com/cb-kubecd/go-test-02.git
  org: cb-kubecd
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: go-test-02
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/cb-kubecd/go-test-02.git
